extends SceneTree

const EDITION_PACK_ADAPTER := preload("res://scripts/edition_pack_adapter.gd")
const EDITION_PACK_READER := preload("res://scripts/edition_pack_reader.gd")
const ACCEPTANCE_TEST := preload("res://tests/acceptance_test.gd")

const PROVENANCE_PATH := "source-media/journey/provenance.json"

# The nine assets that appear in more than one place: one cutout per Family Guest,
# plus the single Birthday Star and the single Rainbow Path reused everywhere.
const SHARED_MEDIA := [
	{"id": "family-guest.mom", "role": "character-layer", "asset": "family-guest-mom.png"},
	{"id": "family-guest.dad", "role": "character-layer", "asset": "family-guest-dad.png"},
	{"id": "family-guest.pop", "role": "character-layer", "asset": "family-guest-pop.png"},
	{"id": "family-guest.gram", "role": "character-layer", "asset": "family-guest-gram.png"},
	{"id": "family-guest.aunt", "role": "character-layer", "asset": "family-guest-aunt.png"},
	{"id": "family-guest.uncle", "role": "character-layer", "asset": "family-guest-uncle.png"},
	{"id": "family-guest.beasley", "role": "character-layer", "asset": "family-guest-beasley.png"},
	{"id": "journey.birthday-star", "role": "sprite", "asset": "birthday-star.png"},
	{"id": "journey.rainbow-path", "role": "treatment", "asset": "rainbow-path.png"},
]

var test: RefCounted = ACCEPTANCE_TEST.new()


func _init() -> void:
	var adapter := EDITION_PACK_ADAPTER.new()
	var pack_root := ProjectSettings.globalize_path(ACCEPTANCE_TEST.PACK_ROOT)
	var prepared: Dictionary = adapter.prepare(pack_root)
	test.expect(prepared.get("ok") == true, "the shared journey media Edition Pack prepares")

	var media_result: Dictionary = adapter.load_media(pack_root, prepared)
	test.expect(media_result.get("ok") == true, "the canonical media index loads")
	var media_by_id: Dictionary = {}
	if media_result.get("ok") == true:
		for media_value: Variant in media_result.value.get("media", []):
			if media_value is Dictionary:
				media_by_id[media_value.get("id")] = media_value

	var reader := EDITION_PACK_READER.new()
	var provenance_result: Dictionary = reader.read_json_object(pack_root, PROVENANCE_PATH)
	test.expect(provenance_result.get("ok") == true, "the shared journey media provenance loads")
	var provenance_by_id: Dictionary = {}
	var personalization: Dictionary = {}
	if provenance_result.get("ok") == true:
		personalization = provenance_result.value.get("personalization", {})
		for asset_value: Variant in provenance_result.value.get("assets", []):
			if asset_value is Dictionary:
				provenance_by_id[asset_value.get("id")] = asset_value

	# ADR-0001 bounds these likenesses to written appearance cues.
	test.expect(
		personalization.get("photographsUsed") == false,
		"the record states that no photograph was sent to an image-generation service",
	)

	for entry_value: Variant in SHARED_MEDIA:
		var entry: Dictionary = entry_value
		var media_id: String = entry.get("id")
		var expected_path: String = "source-media/journey/%s" % entry.get("asset")

		var media: Dictionary = media_by_id.get(media_id, {})
		test.expect(media.get("role") == entry.get("role"), "%s is registered with its role" % media_id)
		test.expect(media.get("path") == expected_path, "%s has one canonical source path" % media_id)

		var image_result: Dictionary = (
			adapter.load_png_texture(pack_root, expected_path)
			if media.get("path") == expected_path
			else {}
		)
		test.expect(image_result.get("ok") == true, "%s decodes through the adapter" % media_id)
		test.expect(image_result.get("texture") is Texture2D, "%s becomes an engine-native texture" % media_id)
		test.expect(
			image_result.get("has_transparency") == true,
			"%s is a cutout with genuine alpha transparency" % media_id,
		)
		test.expect(
			image_result.get("transparent_pixel_count", 0) > 1000,
			"transparent pixels surround the complete %s silhouette" % media_id,
		)

		var provenance: Dictionary = provenance_by_id.get(media_id, {})
		test.expect(
			provenance.get("sha256") == image_result.get("sha256"),
			"%s provenance records the bytes actually on disk" % media_id,
		)
		var generation: Dictionary = provenance.get("generation", {})
		test.expect(
			str(generation.get("prompt", "")).length() > 0,
			"%s provenance records the exact prompt that produced it" % media_id,
		)
		test.expect(
			generation.get("providerHeadquarters") == "United States",
			"%s was generated by a provider billed from the United States" % media_id,
		)

	test.finish(self, "shared journey media acceptance")
